export const categories = [
  "All",
  "Children",
  "Youth",
  "Churches",
  "Feeding Program",
  "Community",
];

// Image filename prefixes mapped to categories
const categoryMapping: Record<string, string> = {
  "sponsored-child": "Children",
  "child-education": "Children",
  "child-sponsorship": "Children",
  "children-learning": "Children",
  "filipino-children": "Children",
  "youth-camp": "Youth",
  "youth-leadership": "Youth",
  "youth-ministry": "Youth",
  "filipino-youth": "Youth",
  "church-worship": "Churches",
  "church-service": "Churches",
  "pastor-training": "Churches",
  "bible-study": "Churches",
  "feeding-program": "Feeding Program",
  "feeding-ministry": "Feeding Program",
  "children-nutrition": "Feeding Program",
  "meal-program": "Feeding Program",
  "community-outreach": "Community",
  "church-community": "Community",
  "volunteer-ministry": "Community",
  "christian-outreach": "Community",
  "mission-work": "Community",
  "ministry-philippines": "Community",
  "nonprofit-ministry": "Community",
  "child-church-partners": "Community",
};

function generateCaption(filename: string): string {
  const name = filename.replace(/\.[^/.]+$/, "");
  const withoutNumber = name.replace(/-\d+$/, "");
  return withoutNumber
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

function generateAltText(filename: string): string {
  const caption = generateCaption(filename);
  return `${caption} - Filipino non-profit Child & Church Partners International`;
}

function getCategory(filename: string): string {
  for (const [prefix, category] of Object.entries(categoryMapping)) {
    if (filename.startsWith(prefix)) {
      return category;
    }
  }
  return "Community";
}

export interface GalleryImage {
  src: string;
  alt: string;
  category: string;
  caption: string;
}

export const galleryImages: GalleryImage[] = [
  // Children
  "sponsored-child-philippines-002.jpg",
  "sponsored-child-philippines-003.jpg",
  "sponsored-child-philippines-004.jpg",
  "sponsored-child-philippines-005.jpeg",
  "sponsored-child-philippines-006.jpeg",
  "sponsored-child-philippines-007.jpg",
  "sponsored-child-philippines-008.jpeg",
  "sponsored-child-philippines-009.jpg",
  "sponsored-child-philippines-010.jpg",
  "child-education-support-002.jpeg",
  "child-education-support-003.jpg",
  "child-education-support-004.jpeg",
  "child-education-support-005.jpg",
  "child-education-support-006.jpg",
  "child-education-support-007.jpg",
  "child-education-support-008.jpg",
  "child-education-support-009.jpg",
  "child-education-support-010.jpg",
  "child-sponsorship-program-001.jpeg",
  "child-sponsorship-program-002.jpg",
  "child-sponsorship-program-003.jpeg",
  "child-sponsorship-program-004.jpeg",
  "child-sponsorship-program-005.jpg",
  "child-sponsorship-program-006.jpeg",
  "child-sponsorship-program-007.jpeg",
  "child-sponsorship-program-008.jpeg",
  "child-sponsorship-program-009.jpeg",
  "children-learning-philippines-001.jpg",
  "children-learning-philippines-002.jpg",
  "children-learning-philippines-003.jpeg",
  "children-learning-philippines-004.jpg",
  "children-learning-philippines-005.jpeg",
  "children-learning-philippines-006.jpeg",
  "children-learning-philippines-007.jpg",
  "children-learning-philippines-008.jpeg",
  "children-learning-philippines-009.jpeg",
  "filipino-children-ministry-001.jpg",
  "filipino-children-ministry-002.jpeg",
  "filipino-children-ministry-003.jpeg",
  "filipino-children-ministry-004.jpg",
  "filipino-children-ministry-005.jpeg",
  "filipino-children-ministry-006.jpg",
  "filipino-children-ministry-007.jpg",
  "filipino-children-ministry-008.jpeg",
  "filipino-children-ministry-009.jpeg",
  // Youth
  "youth-camp-philippines-001.jpeg",
  "youth-camp-philippines-002.jpg",
  "youth-camp-philippines-003.jpeg",
  "youth-camp-philippines-004.jpg",
  "youth-camp-philippines-005.jpg",
  "youth-camp-philippines-006.jpg",
  "youth-camp-philippines-007.jpeg",
  "youth-camp-philippines-008.jpeg",
  "youth-camp-philippines-009.jpg",
  "youth-leadership-training-001.jpeg",
  "youth-leadership-training-002.jpg",
  "youth-leadership-training-003.jpeg",
  "youth-leadership-training-004.jpeg",
  "youth-leadership-training-005.jpeg",
  "youth-leadership-training-006.jpg",
  "youth-leadership-training-007.jpg",
  "youth-leadership-training-008.jpeg",
  "youth-leadership-training-009.jpg",
  "youth-ministry-worship-001.jpeg",
  "youth-ministry-worship-002.jpg",
  "youth-ministry-worship-003.jpg",
  "youth-ministry-worship-004.jpg",
  "youth-ministry-worship-005.jpeg",
  "youth-ministry-worship-006.jpg",
  "youth-ministry-worship-007.jpg",
  "youth-ministry-worship-008.jpg",
  "youth-ministry-worship-009.jpeg",
  "filipino-youth-gathering-001.jpg",
  "filipino-youth-gathering-002.jpg",
  "filipino-youth-gathering-003.jpeg",
  "filipino-youth-gathering-004.jpg",
  "filipino-youth-gathering-005.jpg",
  "filipino-youth-gathering-006.jpg",
  "filipino-youth-gathering-007.jpg",
  "filipino-youth-gathering-008.jpeg",
  "filipino-youth-gathering-009.jpg",
  // Churches
  "church-worship-philippines-001.jpg",
  "church-worship-philippines-002.jpeg",
  "church-worship-philippines-003.jpeg",
  "church-worship-philippines-004.jpg",
  "church-worship-philippines-005.jpg",
  "church-worship-philippines-006.jpeg",
  "church-worship-philippines-007.jpeg",
  "church-worship-philippines-008.jpeg",
  "church-worship-philippines-009.jpg",
  "church-service-philippines-001.jpeg",
  "church-service-philippines-002.jpg",
  "church-service-philippines-003.jpeg",
  "church-service-philippines-004.jpeg",
  "church-service-philippines-005.jpg",
  "church-service-philippines-006.jpeg",
  "church-service-philippines-007.jpeg",
  "church-service-philippines-008.jpeg",
  "church-service-philippines-009.jpg",
  "pastor-training-philippines-001.jpg",
  "pastor-training-philippines-002.jpg",
  "pastor-training-philippines-003.jpeg",
  "pastor-training-philippines-004.jpg",
  "pastor-training-philippines-005.jpg",
  "pastor-training-philippines-006.jpg",
  "pastor-training-philippines-007.jpg",
  "pastor-training-philippines-008.jpeg",
  "pastor-training-philippines-009.jpeg",
  "bible-study-fellowship-001.jpeg",
  "bible-study-fellowship-002.jpeg",
  "bible-study-fellowship-003.jpeg",
  "bible-study-fellowship-004.jpeg",
  "bible-study-fellowship-005.jpg",
  "bible-study-fellowship-006.jpeg",
  "bible-study-fellowship-007.jpg",
  "bible-study-fellowship-008.jpeg",
  "bible-study-fellowship-009.jpg",
  // Feeding Program
  "feeding-program-philippines-001.jpeg",
  "feeding-program-philippines-002.jpeg",
  "feeding-program-philippines-003.jpg",
  "feeding-program-philippines-004.jpg",
  "feeding-program-philippines-007.jpg",
  "feeding-program-philippines-008.jpg",
  "feeding-program-philippines-009.jpg",
  "feeding-ministry-children-001.jpg",
  "feeding-ministry-children-002.jpeg",
  "feeding-ministry-children-003.jpeg",
  "feeding-ministry-children-004.jpg",
  "feeding-ministry-children-005.jpg",
  "feeding-ministry-children-006.jpg",
  "feeding-ministry-children-007.jpg",
  "feeding-ministry-children-008.jpeg",
  "feeding-ministry-children-009.jpeg",
  "children-nutrition-outreach-001.jpeg",
  "children-nutrition-outreach-002.jpg",
  "children-nutrition-outreach-003.jpeg",
  "children-nutrition-outreach-004.jpg",
  "children-nutrition-outreach-005.jpeg",
  "children-nutrition-outreach-006.jpg",
  "children-nutrition-outreach-007.jpg",
  "children-nutrition-outreach-008.jpg",
  "children-nutrition-outreach-009.jpeg",
  "meal-program-filipinos-001.jpeg",
  "meal-program-filipinos-002.jpeg",
  "meal-program-filipinos-003.jpeg",
  "meal-program-filipinos-004.jpg",
  "meal-program-filipinos-005.jpg",
  "meal-program-filipinos-006.jpg",
  "meal-program-filipinos-007.jpg",
  "meal-program-filipinos-008.jpeg",
  "meal-program-filipinos-009.jpeg",
  // Community
  "community-outreach-event-003.jpeg",
  "community-outreach-event-004.jpg",
  "community-outreach-event-005.jpeg",
  "community-outreach-event-006.jpeg",
  "community-outreach-event-007.jpg",
  "community-outreach-event-008.jpg",
  "community-outreach-event-009.jpg",
  "church-community-outreach-001.jpeg",
  "church-community-outreach-002.jpg",
  "church-community-outreach-003.jpg",
  "church-community-outreach-004.jpg",
  "church-community-outreach-005.jpeg",
  "church-community-outreach-006.jpeg",
  "church-community-outreach-007.jpeg",
  "church-community-outreach-008.jpeg",
  "church-community-outreach-009.jpeg",
  "church-community-service-001.jpeg",
  "church-community-service-002.jpeg",
  "church-community-service-003.jpg",
  "church-community-service-004.jpeg",
  "church-community-service-005.jpg",
  "church-community-service-006.jpeg",
  "church-community-service-007.jpg",
  "church-community-service-008.jpeg",
  "church-community-service-009.jpg",
  "volunteer-ministry-philippines-001.jpeg",
  "volunteer-ministry-philippines-002.jpeg",
  "volunteer-ministry-philippines-003.jpg",
  "volunteer-ministry-philippines-004.jpeg",
  "volunteer-ministry-philippines-005.jpg",
  "volunteer-ministry-philippines-006.jpg",
  "volunteer-ministry-philippines-007.jpeg",
  "volunteer-ministry-philippines-008.jpg",
  "volunteer-ministry-philippines-009.jpg",
  "christian-outreach-philippines-001.jpg",
  "christian-outreach-philippines-002.jpg",
  "christian-outreach-philippines-003.jpeg",
  "christian-outreach-philippines-004.jpg",
  "christian-outreach-philippines-005.jpeg",
  "christian-outreach-philippines-006.jpeg",
  "christian-outreach-philippines-007.jpeg",
  "christian-outreach-philippines-008.jpg",
  "christian-outreach-philippines-009.jpeg",
  "mission-work-philippines-001.jpeg",
  "mission-work-philippines-003.jpeg",
  "mission-work-philippines-004.jpg",
  "mission-work-philippines-005.jpg",
  "mission-work-philippines-006.jpeg",
  "mission-work-philippines-007.jpeg",
  "mission-work-philippines-008.jpeg",
  "mission-work-philippines-009.jpeg",
  "ministry-philippines-ccpi-001.jpg",
  "ministry-philippines-ccpi-002.jpg",
  "ministry-philippines-ccpi-003.jpg",
  "ministry-philippines-ccpi-004.jpg",
  "ministry-philippines-ccpi-005.jpeg",
  "ministry-philippines-ccpi-006.jpeg",
  "ministry-philippines-ccpi-007.jpg",
  "ministry-philippines-ccpi-008.jpeg",
  "ministry-philippines-ccpi-009.jpg",
  "nonprofit-ministry-philippines-001.jpg",
  "nonprofit-ministry-philippines-002.jpg",
  "nonprofit-ministry-philippines-003.jpg",
  "nonprofit-ministry-philippines-004.jpeg",
  "nonprofit-ministry-philippines-005.jpg",
  "nonprofit-ministry-philippines-006.jpeg",
  "nonprofit-ministry-philippines-007.jpg",
  "nonprofit-ministry-philippines-008.jpeg",
  "nonprofit-ministry-philippines-009.jpg",
  "child-church-partners-ministry-001.jpg",
  "child-church-partners-ministry-002.jpg",
  "child-church-partners-ministry-003.jpeg",
  "child-church-partners-ministry-004.jpeg",
  "child-church-partners-ministry-005.jpeg",
  "child-church-partners-ministry-006.jpeg",
  "child-church-partners-ministry-007.jpg",
  "child-church-partners-ministry-008.jpeg",
  "child-church-partners-ministry-009.jpg",
].map((filename) => ({
  src: `/images/photo-gallery/${filename}`,
  alt: generateAltText(filename),
  category: getCategory(filename),
  caption: generateCaption(filename),
}));

// Pre-compute category counts
export const categoryCounts: Record<string, number> = {
  All: galleryImages.length,
};
galleryImages.forEach((img) => {
  categoryCounts[img.category] = (categoryCounts[img.category] || 0) + 1;
});
